# Generated by Django 5.2.8 on 2025-11-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('piscinas', '0003_piscina_imagem'),
        ('usuarios', '0002_profile_cpf_profile_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_reservas', to='usuarios.profile')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='piscinas.piscina')),
            ],
        ),
    ]
