# Generated by Django 5.2.8 on 2025-11-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='resposta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
