# Generated by Django 5.2.8 on 2025-11-07 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piscina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('cidade', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piscinas', to='usuarios.profile')),
            ],
        ),
    ]
