# Generated by Django 5.2.8 on 2025-11-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscina',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
