# Generated by Django 5.2.8 on 2025-11-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscinas', '0002_piscina_preco_diaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='piscina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='piscinas_fotos/'),
        ),
    ]
