# Generated by Django 5.2.8 on 2025-11-10 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piscinas', '0003_piscina_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piscina',
            name='imagem',
        ),
        migrations.CreateModel(
            name='PiscinaImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='piscinas_fotos/')),
                ('piscina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='piscinas.piscina')),
            ],
        ),
    ]
